
# https://github.com/vegasbrianc/prometheus/blob/master/README.md

version: "3.7"

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  grafana:
    image: grafana/grafana:6.7.2
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - 3030:3000
    env_file:
      - ./grafana/config.monitoring
    links:
      - prometheus:prometheus
    depends_on:
      - prometheus

  prometheus: # https://hub.docker.com/r/prom/prometheus
    image: prom/prometheus:v2.17.1
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    links:
      - alertmanager:alertmanager
      - node-exporter:node-exporter

  alertmanager: # https://hub.docker.com/r/prom/alertmanager
    image: quay.io/prometheus/alertmanager:v0.20.0
    container_name: alertmanager
    volumes:
      - ./alertmanager/config.yml:/etc/alertmanager/config.yml
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    ports:
      - 9093:9093
    links:
      - alert-manager-dingtalk:alert-manager-dingtalk

  alert-manager-dingtalk:
    image: lx1036/alert-manager-dingtalk:v1.0.0
    container_name: alert-manager-dingtalk
    command:
      - '--url=${DINGTALKURL}'
    ports:
      - 8800:8080

  node-exporter: # https://hub.docker.com/r/prom/node-exporter
    image: prom/node-exporter:v0.18.1
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points'
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100

