apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "chaos-delay-request"
specs:
  - endpointSelector:
      matchLabels:
        app: deathstar
    ingress:
      - toPorts:
          - ports:
              - port: "80"
                protocol: TCP
            rules:
              l7proto: chaos
              l7:
                - probability: "0.5"
                  delay-request: 1s
