apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
commonLabels:
  app.kubernetes.io/name: grafana
  app.kubernetes.io/part-of: ingress-nginx
resources:
  - deployment.yml
  - service.yml
images:
  - name: grafana/grafana
    newTag: 6.7.2
