
#- name: "copy files"
#  copy:
#    src: '{{item}}'
#    dest: '/root/{{item}}'
#    owner: root
#    group: root
#    mode: '0644'
#  with_items:
#    - server_a
#  tags:
#    - push

- name: "template conf file"
  template:
    src: config_a.ini.j2
    dest: /root/config_a.ini
    owner: root
    group: root
    mode: '0644'
  with_items:
    - config_a.ini
  tags:
    - push
    - conf
