version: "3.7"

services:
  openresty:
    build:
      context: ./nginx
    container_name: openresty
    ports:
      - "${DEV_PORT}:80"
      - "${PROMETHEUS_PORT}:8001"
    networks:
      - default

networks:
  default:
    external:
      name: ${DEV_USER}
