version: "3.7"

services:
  openresty:
    build:
      context: ./nginx
    container_name: openresty
    ports:
      - "${NGINX_PORT}:80"
      - "${NGINX_PROMETHEUS_PORT}:8001"
    links:
      - golang:goproxy
    networks:
      - default

  golang:
    build:
      context: ./golang
    container_name: golang
    ports:
      - "${GOLANG_PORT}:8080"
      - "${GOLANG_PROMETHEUS_PORT}:18081"
    networks:
      - default

networks:
  default:
    external:
      name: ${DEV_USER}
