
version: '3'
services:
  redis:
    image: 'redis:5.0.7'
    ports:
      - '6379:6379'

  redis-password:
    image: 'redis:5.0.7'
    command: '/usr/local/bin/redis-server --port 6380 --requirepass redis-password'
    ports:
      - '6380:6380'

  redis-cluster:
    image: 'grokzen/redis-cluster'
    ports:
      - 7000:7000
      - 7001:7001
      - 7002:7002
      - 7003:7003
      - 7004:7004
      - 7005:7005
