users:
  - id: 1
    name: "admin"
    password: "password"
    salt: "abc123"
    email: "admin@example.com"
    display: "Admin"
    comment: "This is a super user for k8s ui"
    type: 1
    admin: 1
    last_login: "2020-02-03 00:00:00"
    last_ip: "127.0.0.1"
  - id: 2
    name: "developer"
    password: "password"
    salt: "abc123"
    email: "developer@example.com"
    display: "Developer"
    comment: "This is a developer user for k8s ui"
    type: 0
    admin: 0
    last_login: "2020-02-03 00:00:00"
    last_ip: "127.0.0.1"
configs:
  - id: 1
    name: "system.api-name-generate-rule"
    value: "join"
  - id: 2
    name: "system.external-ip"
    value: "true"
  - id: 3
    name: "system.monitor-uri"
    value: "https://prometheus.lx1036.cloud"
  - id: 4
    name: "system.oauth2-title"
    value: "域账号登录"
  - id: 5
    name: "system.title"
    value: "K8S-UI"
notifications:
  - id: 1
    type: "info"
    title: "this is a notification from admin"
    message: "this is a message from admin, this is a message from admin"
    from_user_id: 1
    level: 1
    is_published: true
  - id: 2
    type: "danger"
    title: "this is another notification from admin"
    message: "this is another message from admin, this is another message from admin"
    from_user_id: 1
    level: 1
    is_published: true
notification_logs:
  - id: 1
    user_id: 1
    notification_id: 1
    is_read: false
  - id: 2
    user_id: 1
    notification_id: 2
    is_read: false
namespaces:
  - id: 1
    name: "default"
    kube_namespace: "default"
    meta_data: "meta_data"
apps:
  - id: 1
    name: app_demo
    namespace_id: 1
    meta_data: "meta_data"
    description: "description for app_demo"
    user_id: 1
groups:
  - id: 1
    name: "master"
    comment: "group comment"
    type: 1
namespace_users:
  - namespace_id: 1
    user_id: 1
    group_id: 1
clusters:
  - id: 1
    name: "minikube"
    display_name: "minikube"
    meta_data: "meta_data"
    master: "minikube"
    kube_config: '
      {
        \"apiVersion\":\"v1\",
        \"clusters\":[
          {
            \"name\":\"minikube\",
            \"cluster\":{
              \"server\":\"https://192.168.64.15:8443\",
              \"certificate-authority\":\"/Users/lx1036/.minikube/ca.crt\"
            }
          }
        ],
        \"contexts\":[
          {
            \"name\":\"minikube\",
            \"context\":{
              \"cluster\":\"minikube\",
              \"user\":\"minikube\"
            }
          }
        ],
        \"current-context\":\"minikube\",
        \"kind\":\"Config\",
        \"preferences\":{},
        \"users\": [
          {
            \"name\": \"minikube\",
            \"user\": {
              \"client-certificate\": \"/Users/lx1036/.minikube/client.crt\",
              \"client-key\": \"/Users/lx1036/.minikube/client.key\"
            }
          }
        ]
      }
    '
    description: "minikube for test"
    status: 0
