version: "3.7"

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  openresty:
    build:
      context: ./nginx
    container_name: openresty
    ports:
      - "${NGINX_PORT}:80"
      - "${NGINX_PROMETHEUS_PORT}:8001"
    links:
      - golang:goproxy
    networks:
      - default

  golang:
    build:
      context: ./golang
    container_name: golang
    ports:
      - "${GOLANG_PORT}:8080"
      - "${GOLANG_PROMETHEUS_PORT}:18081"
    networks:
      - default

  prometheus: # https://hub.docker.com/r/prom/prometheus
    image: prom/prometheus:v2.17.1
    container_name: prometheus-meetup
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports: # open http://meetup.lx1036.com:9090/graph
      - "${PROMETHEUS_PORT}:9090"
    links:
#      - alertmanager:alertmanager
      - openresty:openresty-proxy

#  alertmanager: # https://hub.docker.com/r/prom/alertmanager
#    image: quay.io/prometheus/alertmanager:v0.20.0
#    container_name: alertmanager
#    volumes:
#      - ./alertmanager/config.yml:/etc/alertmanager/config.yml
#    command:
#      - '--config.file=/etc/alertmanager/config.yml'
#      - '--storage.path=/alertmanager'
#    ports:
#      - 9093:9093
#    links:
#      - alert-manager-dingtalk:alert-manager-dingtalk
#
#  alert-manager-dingtalk:
#    image: lx1036/alert-manager-dingtalk:v1.0.0
#    container_name: alert-manager-dingtalk
#    command:
#      - '--url=${DINGTALKURL}'
#    ports:
#      - 8800:8080

  grafana:
    image: grafana/grafana:6.7.2
    container_name: grafana-meetup
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - "${GRAFANA_PORT}:3000"
    env_file:
      - ./grafana/config.monitoring
    links:
      - prometheus:prometheus-proxy
    depends_on:
      - prometheus

networks:
  default:
    external:
      name: ${DEV_USER}
