
# https://prometheus.io/docs/alerting/configuration/#configuration-file

route:
  receiver: 'dingtalk'
#  routes:
#    - receiver: 'slack'
#    - receiver: 'dingding'

receivers:
  - name: 'dingtalk' # https://yunlzheng.gitbook.io/prometheus-book/parti-prometheus-ji-chu/alert/alert-manager-use-receiver/alert-manager-extension-with-webhook
#    email_configs:
#      - to: "lx1036@126.com"
    webhook_configs:
      - url: 'http://alert-manager-dingtalk:8080/webhook'
        send_resolved: true
  - name: "slack" # 验证：docker run --rm -it busybox sh -c "while true; do :; done", Slack 会收到消息
    slack_configs:
      - send_resolved: true
        username: 'lx1036'
        channel: 'code'
        api_url: 'https://hooks.slack.com/services/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'
