version: "3"
services:
  openresty:
    image: openresty/openresty
    container_name: php-fpm-exporter-openresty
    volumes:
      - "./openresty/nginx.conf:/etc/nginx/nginx.conf"
      - "./openresty/conf.d/default.conf:/etc/nginx/conf.d/default.conf"
    links:
      - php-fpm:php-fpm-proxy
    ports:
      - "8080:80"
    networks:
      - default
  php-fpm:
    image: lx1036/php-fpm-exporter/php-fpm:7.4
    container_name: php-fpm-exporter-php-fpm
    expose:
      - "9090"
    networks:
      - default

networks:
  default:
    external:
      name: ${DEV_USER}
