apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: etcd
  name: etcd
  namespace: monitoring
spec:
  endpoints:
    - interval: 30s
      scheme: https
      port: port
      tlsConfig:
        caFile: /etc/prometheus/secrets/etcd-certs/ca.pem
        certFile: /etc/prometheus/secrets/etcd-certs/etcd.pem
        insecureSkipVerify: true
        keyFile: /etc/prometheus/secrets/etcd-certs/etcd-key.pem
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      k8s-app: etcd
